---
- name: "GA4GH BROKER - Ensure that directory are created"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ ga4gh_broker_dirs }}"

- name: "GA4GH BROKER - Copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ ga4gh_broker_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ ga4gh_broker_files }}"
  notify: "docker ga4gh_broker restart"

- name: "GA4GH BROKER - Create files from template"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ ga4gh_broker_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ ga4gh_broker_templates }}"
  notify: "docker ga4gh_broker restart"

- name: "GA4GH BROKER - Create docker-compose.yml from template"
  template:
    src: "{{ ga4gh_broker_docker_compose_template }}.j2"
    dest: "{{ ga4gh_broker_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - upgrade_docker_containers
    - ga4gh_broker_upgrade_docker_container
  notify: "docker ga4gh_broker restart"

- name: "GA4GH BROKER - site-specific tasks"
  when: ga4gh_broker_site_specific_tasks is defined
  include_tasks:
    file: "files/{{ ga4gh_broker_site_specific_tasks }}"
    apply:
      tags:
        - site_specific
        - ga4gh_broker_site_specific
  tags:
    - site_specific
    - ga4gh_broker_site_specific

- name: "GA4GH BROKER - Start docker image"
  community.docker.docker_compose_v2:
    project_src: "{{ ga4gh_broker_path }}"
    state: present
    pull: always
  tags:
    - upgrade_docker_containers
    - ga4gh_broker_upgrade_docker_container
