---
- name: "SIMPLESAMLPHP - Ensure that directory are created"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ simplesamlphp_dirs }}"

- name: "SIMPLESAMLPHP - Copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ simplesamlphp_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ simplesamlphp_files }}"
  notify: "docker simplesamlphp restart"

- name: "SIMPLESAMLPHP - Create files from template"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ simplesamlphp_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ simplesamlphp_templates }}"
  notify: "docker simplesamlphp restart"

- name: "SIMPLESAMLPHP - Create docker-compose.yml from template"
  template:
    src: "{{ simplesamlphp_docker_compose_template }}.j2"
    dest: "{{ simplesamlphp_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - upgrade_docker_containers
    - simplesamlphp_upgrade_docker_container
  notify: "docker simplesamlphp restart"

- name: "SIMPLESAMLPHP - site-specific tasks"
  when: simplesamlphp_site_specific_tasks is defined
  include_tasks:
    file: "files/{{ simplesamlphp_site_specific_tasks }}"
    apply:
      tags:
        - site_specific
        - simplesamlphp_site_specific
  tags:
    - site_specific
    - simplesamlphp_site_specific

- name: "SIMPLESAMLPHP - Start docker image"
  community.docker.docker_compose_v2:
    project_src: "{{ simplesamlphp_path }}"
    state: present
    pull: always
  tags:
    - upgrade_docker_containers
    - simplesamlphp_upgrade_docker_container

- name: "SIMPLESAMLPHP - Cronjobs"
  cron:
    name: "{{ item. name }}"
    user: "{{ item.user|default('root') }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour|default('*') }}"
    minute: "{{ item.minute|default('*') }}"
  loop: "{{ simplesamlphp_cronjobs }}"

- name: "SIMPLESAMLPHP - Force cronjobs when install"
  shell: "{{ item.job }}"
  when: force=="true"
  loop: "{{ simplesamlphp_cronjobs }}"
